version: "3.7"
services:
  api_service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
#    networks:
#      - springapimysql-net
    environment:
      SPRING_DATASOURCE_URL: ${RDS_URL}
      SPRING_DATASOURCE_USERNAME: ${RDS_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${RDS_PASSWORD}
#    environment:
#      - spring.datasource.url=jdbc:mysql://mysqldb:3307/capstone?allowPublicKeyRetrieval=true
    depends_on:
      - redis
#      - mysqldb

    volumes:
      - .m2:/root/.m2
  redis:
    image: redis
    ports:
      - 6379:6379
#  mysqldb:
#    image: "mysql:8.0"
#    restart: always
#    ports:
#      - 3307:3307
#    networks:
#      - springapimysql-net
#    environment:
#      MYSQL_DATABASE: capstone
#      MYSQL_ROOT_PASSWORD: Health!0930
#networks:
#  springapimysql-net: